version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    hostname: mysql
    environment:
      - MYSQL_DATABASE=deeptrain
      - MYSQL_ROOT_PASSWORD=zmh200904
    networks:
      - db_network

  redis:
    image: redis:latest
    hostname: redis
    restart: always
    networks:
      - db_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL=mysql
      - DOCKER=true
    command: bash -c "python manage.py migrate && gunicorn -c gunicorn.conf.py Deeptrain.wsgi:application"
    depends_on:
      - mysql
      - redis
    networks:
      - db_network
      - app_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /compose/nginx/nginx.conf/:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app_network
    privileged: true

networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge
